FROM ubuntu

#instala os pacotes necessários
RUN apt-get update && \
    apt-get install -y openssh-client git vim nodejs npm mysql-client mysql-server

#faz clone to repositório do github com a configuração do webserver
ARG SHA=LATEST
RUN SHA=${SHA} \
    git clone https://github.com/Hugo1506/projeto_final_webserver.git


#instala as dependencias para a frontend 
RUN cd projeto_final_webserver/frontend && npm install -g depcheck && npm fund

#inicia o mysql e cria o utilizador hugo
RUN service mysql start && \
    mysql -u root -e "CREATE USER 'hugo'@'localhost' IDENTIFIED WITH mysql_native_password BY 'hugo';" && \
    mysql -u root -e "FLUSH PRIVILEGES;" && \
    mysql -u root -e "CREATE DATABASE projeto_final;" && \
    mysql -u root projeto_final < /projeto_final_webserver/database_dump.sql && \
    mysql -u root -e "GRANT ALL PRIVILEGES ON projeto_final.* TO 'hugo'@'localhost';" && \
    mysql -u root -e "FLUSH PRIVILEGES;"

RUN chmod +x projeto_final_webserver/start_script.bash

CMD projeto_final_webserver/start_script.bash

